{"name": "test_login[wrong_user-wrong_pass-False]", "status": "broken", "statusDetails": {"message": "AttributeError: 'LoginPage' object has no attribute 'get_error_message'", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"3cc1ca189b04bf60788cc693771d2980\")>, username = 'wrong_user', password = 'wrong_pass', is_valid = False\n\n    @pytest.mark.ui\n    @pytest.mark.parametrize(\"username,password,is_valid\", [\n        (\"standard_user\", \"secret_sauce\", True),\n        (\"locked_out_user\", \"secret_sauce\", False),\n        (\"wrong_user\", \"wrong_pass\", False),\n    ])\n    def test_login(driver, username, password, is_valid):\n        login_page = LoginPage(driver)\n        login_page.open()\n        login_page.login(username, password)\n        if is_valid:\n            products_page = ProductsPage(driver)\n            assert products_page.is_loaded()\n        else:\n>           assert \"Epic sadface\" in login_page.get_error_message()\n                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE           AttributeError: 'LoginPage' object has no attribute 'get_error_message'\n\ntests/ui/test_ui_login.py:19: AttributeError"}, "parameters": [{"name": "username", "value": "'wrong_user'"}, {"name": "password", "value": "'wrong_pass'"}, {"name": "is_valid", "value": "False"}], "start": 1749134610027, "stop": 1749134610320, "uuid": "ff7cfc1d-e615-4979-8e63-0347ad8c78de", "historyId": "1dd31125eeb64c72c1f03c32cec57760", "testCaseId": "4781fd2326e41bcc4eaaa21f5fb7f5a6", "fullName": "tests.ui.test_ui_login#test_login", "labels": [{"name": "tag", "value": "ui"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_ui_login"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "19815-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_ui_login"}]}